[package]
authors = ["George Pittarelli <g@gjp.cc>"]
license = "MIT OR Apache-2.0"
name = "to-and-from"
version = "0.1.0"

[dependencies]
combine = "2.5.2"
csv = "1.0.0"
itertools = "0.7.7"
lazy_static = "1.0.0"
num = "0.1.42"
petgraph = "0.4.11"
serde = "1.0.30"
serde_json = "1.0.11"
